-- DineroMundo Phase 7: Supabase/PostgreSQL schema
-- Run in a NEW Supabase project's SQL editor. Never use a service_role key in browser code.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '' check(char_length(full_name)<=120),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.businesses(
  id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Mi negocio' check(char_length(name) between 1 and 160), contact_name text not null default '', email text not null default '', phone text not null default '', address text not null default '', city text not null default '', state_region text not null default '', postal_code text not null default '', country text not null default '', tax_id text not null default '', website text not null default '',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_user_id)
);
create table if not exists public.customers(
  business_id uuid not null references public.businesses(id) on delete cascade,id text not null,type text not null default 'person' check(type in('person','company')),name text not null default '',company text not null default '',contact_person text not null default '',tax_id text not null default '',email text not null default '',phone text not null default '',address text not null default '',city text not null default '',state_region text not null default '',postal_code text not null default '',country text not null default '',notes text not null default '',status text not null default 'active' check(status in('active','archived')),payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(business_id,id)
);
create table if not exists public.quotes(
  business_id uuid not null references public.businesses(id) on delete cascade,id text not null,customer_id text,quote_number text not null default '',issue_date date,valid_until date,currency text not null check(currency in('MXN','COP','PEN','CLP','ARS','USD','EUR')),status text not null check(status in('borrador','enviada','aceptada','rechazada','vencida')),converted_invoice_id text,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(business_id,id)
);
create table if not exists public.invoices(
  business_id uuid not null references public.businesses(id) on delete cascade,id text not null,customer_id text,source_quote_id text,invoice_number text not null default '',issue_date date,due_date date,currency text not null check(currency in('MXN','COP','PEN','CLP','ARS','USD','EUR')),status text not null check(status in('borrador','emitida','pagada','parcialmente_pagada','vencida','anulada')),payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(business_id,id),foreign key(business_id,source_quote_id) references public.quotes(business_id,id) deferrable initially deferred
);
create table if not exists public.incomes(
  business_id uuid not null references public.businesses(id) on delete cascade,id text not null,customer_id text,invoice_id text,date date not null,amount numeric(18,2) not null check(amount>=0),currency text not null check(currency in('MXN','COP','PEN','CLP','ARS','USD','EUR')),status text not null check(status in('received','pending','cancelled')),category text not null default 'Otro',payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(business_id,id),foreign key(business_id,invoice_id) references public.invoices(business_id,id) deferrable initially deferred
);
create table if not exists public.expenses(
  business_id uuid not null references public.businesses(id) on delete cascade,id text not null,customer_id text,date date not null,amount numeric(18,2) not null check(amount>=0),currency text not null check(currency in('MXN','COP','PEN','CLP','ARS','USD','EUR')),status text not null check(status in('paid','pending','cancelled')),category text not null default 'Otros',payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(business_id,id)
);

create index if not exists customers_business_status_idx on public.customers(business_id,status);create index if not exists quotes_business_date_idx on public.quotes(business_id,issue_date);create index if not exists quotes_customer_idx on public.quotes(business_id,customer_id);create index if not exists invoices_business_due_idx on public.invoices(business_id,due_date);create index if not exists invoices_customer_idx on public.invoices(business_id,customer_id);create index if not exists incomes_business_date_idx on public.incomes(business_id,date);create index if not exists incomes_invoice_idx on public.incomes(business_id,invoice_id);create index if not exists expenses_business_date_idx on public.expenses(business_id,date);
do $$ declare t text;begin foreach t in array array['profiles','businesses','customers','quotes','invoices','incomes','expenses'] loop execute format('drop trigger if exists set_%I_updated_at on public.%I',t,t);execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t);end loop;end $$;

create or replace function public.owns_business(target uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.businesses b where b.id=target and b.owner_user_id=(select auth.uid()))$$;revoke all on function public.owns_business(uuid) from public;grant execute on function public.owns_business(uuid) to authenticated;
alter table public.profiles enable row level security;alter table public.businesses enable row level security;alter table public.customers enable row level security;alter table public.quotes enable row level security;alter table public.invoices enable row level security;alter table public.incomes enable row level security;alter table public.expenses enable row level security;
revoke all on table public.profiles,public.businesses,public.customers,public.quotes,public.invoices,public.incomes,public.expenses from anon,authenticated;grant select,insert,update on public.profiles,public.businesses to authenticated;grant select,insert,update,delete on public.customers,public.quotes,public.invoices,public.incomes,public.expenses to authenticated;
create policy "own profile select" on public.profiles for select to authenticated using((select auth.uid())=id);create policy "own profile update" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);create policy "own business select" on public.businesses for select to authenticated using((select auth.uid())=owner_user_id);create policy "own business update" on public.businesses for update to authenticated using((select auth.uid())=owner_user_id) with check((select auth.uid())=owner_user_id);
do $$ declare t text;begin foreach t in array array['customers','quotes','invoices','incomes','expenses'] loop execute format('create policy "owned %s select" on public.%I for select to authenticated using(public.owns_business(business_id))',t,t);execute format('create policy "owned %s insert" on public.%I for insert to authenticated with check(public.owns_business(business_id))',t,t);execute format('create policy "owned %s update" on public.%I for update to authenticated using(public.owns_business(business_id)) with check(public.owns_business(business_id))',t,t);execute format('create policy "owned %s delete" on public.%I for delete to authenticated using(public.owns_business(business_id))',t,t);end loop;end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''));insert into public.businesses(owner_user_id,name,contact_name,email) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'business_name',''),'Mi negocio'),coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.email,''));return new;end$$;drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
