import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const updated='28 de julio de 2026';
const pages=[
  {
    slug:'nosotros',title:'Sobre DineroMundo | Educación financiera en español',description:'Conoce la misión, alcance y límites de DineroMundo, una plataforma de educación financiera y herramientas gratuitas en español.',h1:'Sobre DineroMundo',eyebrow:'Quiénes somos',intro:'DineroMundo ofrece herramientas y educación financiera en español para hispanos en Estados Unidos y lectores de América Latina.',
    sections:[
      ['Nuestra misión','Buscamos explicar temas financieros cotidianos con lenguaje claro y ofrecer herramientas que ayuden a formular mejores preguntas. El sitio reúne calculadoras, guías por país, información de proveedores de transferencias, comparaciones educativas y artículos sobre presupuesto, ahorro, crédito, deudas, salarios y seguridad financiera.'],
      ['A quién servimos','El contenido está pensado para personas hispanohablantes que navegan sistemas financieros distintos. Algunas guías se enfocan en Estados Unidos y otras presentan conceptos aplicables en varios países. Siempre indicamos cuando las reglas, productos o prácticas pueden cambiar según la jurisdicción o institución.'],
      ['Lo que DineroMundo no hace','DineroMundo no procesa transferencias ni recibe dinero de los visitantes. No es banco, prestamista, preparador de impuestos, asesor de inversiones, bufete de abogados, institución migratoria ni agencia gubernamental. Tampoco decide aprobaciones, tasas, límites, puntajes o disponibilidad de servicios.'],
      ['Responsabilidad editorial','El equipo editorial de DineroMundo organiza información general y ejemplos educativos. No presentamos biografías o credenciales profesionales inventadas. Los visitantes deben confirmar requisitos, costos, leyes y condiciones vigentes con instituciones financieras, proveedores, autoridades o profesionales apropiados.']
    ]
  },
  {
    slug:'contacto',title:'Contacto y reporte de correcciones | DineroMundo',description:'Consulta cómo reportar errores, enlaces rotos o información desactualizada y qué datos personales nunca debes enviar a DineroMundo.',h1:'Contacto',eyebrow:'Comunicación responsable',intro:'Próximamente habilitaremos un método de contacto directo. Mientras tanto, esta página explica qué reportes podremos recibir y cómo proteger tu información.',
    sections:[
      ['Qué podrás reportar','Cuando exista un canal directo, podrás señalar enlaces rotos, errores técnicos, resultados inesperados en una calculadora, información de proveedores que parezca desactualizada o explicaciones que necesiten mayor claridad. Incluye la URL pública, una descripción concreta y, si corresponde, la fuente oficial que respalda el cambio.'],
      ['Información que no debes enviar','No envíes nombres completos innecesarios, números de cuentas financieras, tarjetas, Seguro Social, ITIN, contraseñas, códigos de seguridad, direcciones, documentos de identidad ni capturas que los muestren. DineroMundo no necesita esos datos para revisar contenido o un error técnico.'],
      ['Transferencias y cuentas','DineroMundo no procesa, rastrea, cancela ni reembolsa transferencias. Para una operación específica, utiliza los canales oficiales del proveedor o institución. No publiques aquí números completos de referencia ni información del destinatario.'],
      ['Correcciones editoriales','Los reportes verificables se evaluarán conforme a nuestra política de correcciones. La ausencia temporal de contacto directo no cambia la recomendación de verificar información financiera actual con una fuente oficial.']
    ]
  },
  {
    slug:'privacidad',title:'Política de privacidad | DineroMundo',description:'Conoce cómo funciona este sitio estático, cómo se procesan los datos de calculadoras y qué información no recopila DineroMundo.',h1:'Política de privacidad',eyebrow:'Privacidad',intro:'Esta política describe el funcionamiento actual de DineroMundo.com como sitio estático y las decisiones de privacidad incorporadas en sus herramientas.',
    sections:[
      ['Sitio estático y datos introducidos','Las calculadoras se ejecutan en el navegador con JavaScript. Los valores se procesan localmente y no se envían a DineroMundo. Algunas calculadoras guardan únicamente sus campos en localStorage para restaurarlos en el mismo dispositivo; puedes eliminarlos mediante “Borrar datos” o las herramientas del navegador.'],
      ['Información que no recopilamos','El sitio no permite crear cuentas y no solicita nombres, correos, números bancarios, tarjetas, Seguro Social, ITIN, credenciales ni documentos. No existe un formulario activo de newsletter o contacto. Los espacios publicitarios son marcadores inactivos y no contienen código publicitario.'],
      ['Cookies, analítica y servicios futuros','La aplicación actual no instala cookies propias ni integra analítica externa. Si en el futuro se incorporan publicidad, analítica, formularios u otros servicios que cambien el tratamiento de datos, esta política deberá actualizarse antes o junto con su implementación.'],
      ['Alojamiento y registros técnicos','La infraestructura de alojamiento, red o navegador puede mantener registros técnicos normales, como dirección IP, agente del navegador, fecha y recurso solicitado. DineroMundo no afirma controlar ni eliminar todos los registros gestionados por GitHub Pages u otros componentes de infraestructura.'],
      ['Enlaces externos y menores','Los enlaces a proveedores e instituciones conducen a sitios con políticas propias. El contenido se dirige a una audiencia general y no está diseñado para recopilar información de menores. Si un menor utiliza el sitio, debe hacerlo con la orientación apropiada de una persona adulta.'],
      ['Actualizaciones y contacto','Podemos actualizar esta política cuando cambien las funciones del sitio. La fecha de revisión aparecerá en esta página. Hasta que exista un método de contacto directo, no envíes información personal por canales no oficiales.']
    ]
  },
  {
    slug:'terminos',title:'Términos y condiciones de uso | DineroMundo',description:'Lee los términos aplicables al uso educativo de DineroMundo, sus calculadoras, contenidos, enlaces externos y limitaciones generales.',h1:'Términos y condiciones',eyebrow:'Condiciones de uso',intro:'Al utilizar DineroMundo aceptas usar sus herramientas y contenidos únicamente como recursos educativos generales.',
    sections:[
      ['Uso educativo','El contenido y los cálculos no crean una relación profesional, fiduciaria, bancaria, legal, fiscal, crediticia o de asesoría. Debes verificar decisiones importantes con la institución, autoridad o profesional apropiado para tu situación y jurisdicción.'],
      ['Exactitud y disponibilidad','Trabajamos para presentar información clara, pero no garantizamos que cada página sea completa, actual o libre de errores, ni que el sitio esté disponible de forma ininterrumpida. Tarifas, productos, reglas, límites y servicios pueden cambiar sin aviso de DineroMundo.'],
      ['Responsabilidad del visitante','Eres responsable de revisar los datos que introduces, interpretar las estimaciones con cuidado y confirmar información de proveedores. No uses una calculadora como estado oficial de un banco, prestamista, autoridad fiscal o servicio de transferencias.'],
      ['Enlaces externos','Los enlaces externos se ofrecen como referencia. DineroMundo no controla su contenido, seguridad, disponibilidad o políticas. Abrir un enlace no constituye respaldo, afiliación ni recomendación individual.'],
      ['Propiedad intelectual y uso prohibido','El texto original, estructura y diseño de DineroMundo están protegidos por las normas aplicables. No debes copiar masivamente el sitio, interferir con su funcionamiento, eludir medidas técnicas, presentar su contenido como propio ni utilizarlo para fraude o actividad ilícita.'],
      ['Limitación y cambios','En la medida permitida, DineroMundo no responde por decisiones o pérdidas basadas únicamente en información general del sitio. Podemos modificar estos términos cuando cambien las funciones. No se declara una jurisdicción gobernante específica porque no existe una publicada en el repositorio.']
    ]
  },
  {
    slug:'aviso-financiero',title:'Aviso financiero y límites de la información | DineroMundo',description:'Comprende por qué el contenido y las calculadoras de DineroMundo son educativos, estimados y no sustituyen asesoría profesional.',h1:'Aviso financiero',eyebrow:'Información importante',intro:'DineroMundo publica educación general y herramientas matemáticas. No ofrece recomendaciones personalizadas ni conoce las circunstancias completas de cada visitante.',
    sections:[
      ['Estimaciones y supuestos','Las calculadoras utilizan datos introducidos por el visitante y fórmulas matemáticas estándar. Los resultados son estimaciones: pueden diferir de estados oficiales por fechas, redondeos, capitalización, cargos, impuestos, políticas o términos contractuales.'],
      ['Proveedores y transferencias','Tarifas, tipos de cambio, métodos, límites, promociones, tiempos y disponibilidad cambian por país y ruta. DineroMundo no garantiza ahorro, velocidad, conversión, recepción ni acceso a un proveedor. Confirma siempre la pantalla final y los términos oficiales.'],
      ['Crédito, banca y préstamos','Los modelos de puntaje y criterios de entidades varían. Nada en el sitio garantiza aprobación, tasa, límite, aumento de puntaje o resultado de una solicitud. La información bancaria también depende del producto, institución y protección aplicable.'],
      ['Impuestos, migración e inversión','La situación fiscal, migratoria, legal y de inversión depende de normas vigentes y circunstancias individuales. DineroMundo no calcula obligaciones fiscales personales, recomienda valores ni interpreta derechos migratorios o legales.'],
      ['Cuándo buscar ayuda','Consulta profesionales cualificados, instituciones financieras o fuentes gubernamentales oficiales cuando una decisión tenga consecuencias importantes. Si enfrentas fraude, dificultad para cubrir necesidades o una disputa, utiliza recursos oficiales apropiados para tu ubicación.']
    ]
  },
  {
    slug:'politica-editorial',title:'Política editorial y transparencia | DineroMundo',description:'Conoce los principios de neutralidad, fuentes, actualizaciones, publicidad, correcciones y transparencia editorial de DineroMundo.',h1:'Política editorial',eyebrow:'Transparencia editorial',intro:'La política editorial define cómo DineroMundo separa educación, publicidad potencial y relaciones comerciales futuras.',
    sections:[
      ['Neutralidad y claridad','Redactamos con tono educativo y evitamos declarar que un proveedor es universalmente mejor, más barato, rápido o seguro. Las comparaciones presentan factores y escenarios sin crear ganadores, puntuaciones o recomendaciones individuales.'],
      ['Información y publicidad','Los espacios publicitarios actuales son marcadores inactivos. Cualquier publicidad futura deberá distinguirse visualmente del contenido y no podrá imitar resultados, botones o cotizaciones. No aceptamos colocación pagada encubierta ni rankings falsos.'],
      ['Fuentes y fechas de revisión','Cuando una afirmación depende de información cambiante, se deben priorizar fuentes oficiales de proveedores, instituciones o autoridades. Las páginas relevantes muestran una fecha de revisión. Esa fecha indica revisión editorial, no garantía de vigencia permanente.'],
      ['Proceso de actualización y correcciones','Los enlaces, funciones y hechos susceptibles de cambio pueden revisarse periódicamente. Un error factual o técnico verificable debe corregirse y, cuando sea significativo, actualizar la fecha de revisión. Los cambios gramaticales menores pueden realizarse sin historial público.'],
      ['Herramientas digitales y revisión','El contenido puede apoyarse en herramientas digitales de redacción y debe revisarse antes de publicarse. DineroMundo no afirma que cada página haya sido revisada por un experto humano acreditado cuando esa revisión no está documentada.'],
      ['Afiliación futura','Actualmente no se utilizan enlaces de afiliados. Una relación futura deberá identificarse claramente y no podrá determinar conclusiones editoriales. Consulta la divulgación de afiliados para el estado vigente.']
    ]
  },
  {
    slug:'metodologia',title:'Metodología de evaluación y cálculo | DineroMundo',description:'Conoce cómo DineroMundo organiza información de proveedores, calcula estimaciones y prepara guías educativas sin datos financieros en vivo.',h1:'Metodología de DineroMundo',eyebrow:'Cómo trabajamos',intro:'Esta metodología explica el marco utilizado para organizar proveedores, comparaciones, calculadoras y guías educativas.',
    sections:[
      ['Proveedores y comparaciones','Revisamos métodos de pago y recepción, acceso en línea, ubicaciones físicas, disponibilidad por ruta, tarifas, tipos de cambio, velocidad, límites, identificación, cancelaciones, reembolsos y atención al cliente. No tenemos acceso a sistemas privados y no mostramos cotizaciones en vivo.'],
      ['Cómo interpretar costos','El costo total puede incluir tarifa visible, diferencia cambiaria, método de pago, recepción y cargos externos. Las páginas explican esos componentes sin inventar precios ni clasificar un proveedor como ganador universal. El visitante debe comparar una misma ruta y confirmar el resultado final.'],
      ['Calculadoras','Las herramientas usan fórmulas matemáticas estándar y supuestos escritos por el usuario. Se ejecutan en el navegador, producen estimaciones y no consultan datos en vivo de bancos, prestamistas, proveedores, autoridades fiscales o mercados. Las fórmulas no sustituyen documentos contractuales.'],
      ['Guías educativas','Las guías resumen conceptos, incluyen ejemplos ficticios y enlazan herramientas relacionadas. Las reglas y prácticas pueden variar por país e institución, por lo que los lectores deben verificar detalles actuales con fuentes oficiales.'],
      ['Revisión y límites','Las fechas de revisión muestran cuándo se evaluó una página. Una actualización puede originarse por cambios públicos, enlaces rotos o reportes verificables. DineroMundo no afirma tener acceso anticipado a cambios ni garantiza que una fuente externa permanezca disponible.']
    ]
  },
  {
    slug:'correcciones',title:'Política de correcciones | DineroMundo',description:'Conoce cómo DineroMundo evalúa y corrige errores factuales, enlaces rotos, problemas técnicos y explicaciones poco claras.',h1:'Política de correcciones',eyebrow:'Exactitud y mejora',intro:'DineroMundo busca corregir errores factuales y técnicos de manera proporcional, transparente y verificable.',
    sections:[
      ['Qué puede corregirse','Una corrección puede abarcar enlaces rotos, información pública desactualizada, errores de cálculo o presentación, rutas internas incorrectas y explicaciones ambiguas. Un desacuerdo basado solamente en preferencia no demuestra necesariamente un error factual.'],
      ['Cómo evaluar un reporte','Revisamos la URL, la afirmación o comportamiento señalado y, cuando corresponde, la fuente oficial disponible. No necesitamos números de cuenta, documentos de identidad ni datos financieros personales para investigar un problema del sitio.'],
      ['Cambios significativos','Una corrección que modifica una conclusión educativa, capacidad de proveedor, resultado técnico o hecho importante debe actualizar la fecha de revisión de la página. Si el contexto lo requiere, puede añadirse una explicación breve del cambio.'],
      ['Cambios menores','Ortografía, puntuación, formato y mejoras de claridad que no cambian el significado pueden realizarse sin un aviso de corrección. No se publica un historial ficticio ni se inventan reportes recibidos.'],
      ['Limitación de contacto','Hasta que exista un método directo, la página de contacto explica el estado actual. Los problemas con una transferencia o cuenta deben dirigirse al proveedor o institución correspondiente.']
    ]
  },
  {
    slug:'divulgacion-afiliados',title:'Divulgación de afiliados | DineroMundo',description:'Consulta el estado actual de afiliación de DineroMundo y cómo se distinguirían futuros enlaces comerciales de la información editorial.',h1:'Divulgación de afiliados',eyebrow:'Relaciones comerciales',intro:'DineroMundo actualmente no utiliza enlaces de afiliados. Los enlaces a proveedores son informativos y no incluyen seguimiento comercial añadido por el sitio.',
    sections:[
      ['Estado actual','No recibimos una comisión cuando un visitante abre los enlaces informativos actuales o utiliza una calculadora. Tampoco existen rankings patrocinados, puntuaciones pagadas ni ofertas creadas para aparentar una relación comercial.'],
      ['Posibles relaciones futuras','Si se añaden programas de afiliación, los enlaces correspondientes deberán llevar una etiqueta clara cerca del enlace o sección. Esta página y la política de privacidad se actualizarán para reflejar cualquier cambio relevante.'],
      ['Independencia editorial','Una compensación futura no deberá determinar conclusiones, ventajas, desventajas o el orden editorial de una comparación. Ningún proveedor podrá presentarse como ganador universal por pagar una comisión.'],
      ['Afiliación y publicidad','Un enlace de afiliado puede generar compensación por una acción; la publicidad gráfica se paga o sirve de otra forma. Son mecanismos distintos y ambos deben separarse visualmente del contenido educativo. Los espacios publicitarios actuales están inactivos.'],
      ['Verificación del visitante','Una divulgación no sustituye la revisión de costos, tasas, límites y condiciones. Confirma todos los términos directamente con el proveedor antes de utilizar un servicio.']
    ]
  }
];

const base=d=>d?'../'.repeat(d):'./';
const nav=(depth,current='')=>{const home=base(depth);const items=[['Inicio',home,'home'],['Enviar dinero',`${home}#enviar-dinero`,'send'],['Calculadoras',`${home}calculadoras/`,'calculadoras'],['Países',`${home}paises/`,'paises'],['Proveedores',`${home}proveedores/`,'proveedores'],['Comparar',`${home}comparar/`,'comparar'],['Aprender',`${home}aprender/`,'aprender'],['Nosotros',`${home}nosotros/`,'nosotros']];return `<nav class="site-nav" id="site-nav" aria-label="Navegación principal">${items.map(([n,u,k])=>`<a href="${u}"${current===k?' aria-current="page"':''}>${n}</a>`).join('')}<a class="btn btn-primary nav-cta" href="${home}calculadoras/">Explorar herramientas</a></nav>`};
const header=(depth,current='')=>{const home=base(depth);return `<a class="skip-link" href="#contenido">Saltar al contenido principal</a><header class="site-header"><div class="container header-inner"><a class="brand" href="${home}" aria-label="DineroMundo, página de inicio"><span>Dinero</span>Mundo</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span class="sr-only">Abrir menú principal</span><span aria-hidden="true"></span><span aria-hidden="true"></span><span aria-hidden="true"></span></button>${nav(depth,current)}</div></header>`};
const footer=depth=>{const home=base(depth);return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a class="brand brand-light" href="${home}"><span>Dinero</span>Mundo</a><p>Educación y herramientas financieras claras para tomar decisiones informadas.</p></div><div><h2>DineroMundo</h2><ul><li><a href="${home}nosotros/">Nosotros</a></li><li><a href="${home}contacto/">Contacto</a></li><li><a href="${home}politica-editorial/">Política editorial</a></li><li><a href="${home}metodologia/">Metodología</a></li><li><a href="${home}correcciones/">Correcciones</a></li></ul></div><div><h2>Recursos</h2><ul><li><a href="${home}calculadoras/">Calculadoras</a></li><li><a href="${home}paises/">Países</a></li><li><a href="${home}proveedores/">Proveedores</a></li><li><a href="${home}comparar/">Comparar</a></li><li><a href="${home}aprender/">Aprender</a></li></ul></div><div><h2>Legal</h2><ul><li><a href="${home}privacidad/">Privacidad</a></li><li><a href="${home}terminos/">Términos</a></li><li><a href="${home}aviso-financiero/">Aviso financiero</a></li><li><a href="${home}divulgacion-afiliados/">Divulgación de afiliados</a></li></ul></div></div><div class="footer-bottom"><p>© <span data-year>${new Date().getFullYear()}</span> DineroMundo.com</p><p>Contenido educativo; verifica información actual con fuentes apropiadas.</p></div></div></footer>`};
const org={'@context':'https://schema.org','@type':'Organization',name:'DineroMundo',url:'https://dineromundo.com/'};
const escapeJson=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const trustPage=p=>{const canonical=`https://dineromundo.com/${p.slug}/`;const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Inicio',item:'https://dineromundo.com/'},{'@type':'ListItem',position:2,name:p.h1,item:canonical}]};const webpage={'@context':'https://schema.org','@type':'WebPage',name:p.h1,description:p.description,url:canonical,inLanguage:'es'};const body=`<main id="contenido"><section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Migas de pan"><ol><li><a href="../">Inicio</a></li><li aria-current="page">${p.h1}</li></ol></nav><p class="eyebrow">${p.eyebrow}</p><h1>${p.h1}</h1><p class="hero-lede">${p.intro}</p><p class="review-date">Última revisión: ${updated}</p></div></section><section class="section"><div class="container legal-layout"><div class="legal-content">${p.sections.map(([h,t])=>`<section><h2>${h}</h2><p>${t}</p></section>`).join('')}</div><aside class="legal-sidebar"><h2>Transparencia</h2><p>Consulta también nuestras políticas relacionadas.</p><ul><li><a href="../politica-editorial/">Política editorial</a></li><li><a href="../metodologia/">Metodología</a></li><li><a href="../correcciones/">Correcciones</a></li><li><a href="../aviso-financiero/">Aviso financiero</a></li></ul></aside></div></section></main>`;return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title}</title><meta name="description" content="${p.description}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${p.title}"><meta property="og:description" content="${p.description}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="DineroMundo"><meta property="og:locale" content="es_US"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${p.title}"><meta name="twitter:description" content="${p.description}"><link rel="icon" href="../assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/css/styles.css"><script type="application/ld+json">${escapeJson(org)}</script><script type="application/ld+json">${escapeJson(breadcrumb)}</script><script type="application/ld+json">${escapeJson(webpage)}</script></head><body>${header(1,p.slug==='nosotros'?'nosotros':'')}${body}${footer(1)}<script src="../assets/js/main.js" defer></script></body></html>`};
for(const p of pages){const d=path.join(root,p.slug);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),trustPage(p))}

const errorBody=`<main id="contenido"><section class="error-page"><div class="container error-card"><p class="eyebrow">Error 404</p><h1>Página no encontrada</h1><p>La dirección puede estar incompleta o la página pudo cambiar. Usa uno de estos enlaces para continuar.</p><div class="button-row"><a class="btn btn-primary" href="./">Inicio</a><a class="btn btn-secondary" href="calculadoras/">Calculadoras</a><a class="btn btn-secondary" href="paises/">Países</a><a class="btn btn-secondary" href="proveedores/">Proveedores</a><a class="btn btn-secondary" href="comparar/">Comparar</a><a class="btn btn-secondary" href="aprender/">Aprender</a></div></div></section></main>`;
fs.writeFileSync(path.join(root,'404.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Página no encontrada | DineroMundo</title><meta name="robots" content="noindex"><meta name="description" content="La página solicitada no se encontró. Regresa al inicio o visita las herramientas y guías de DineroMundo."><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/styles.css"></head><body>${header(0,'')}${errorBody}${footer(0)}<script src="assets/js/main.js" defer></script></body></html>`);

function pageSection(file){const rel=path.relative(root,file).replaceAll('\\','/');if(rel==='index.html')return'home';return rel.split('/')[0]}
function normalizeDescription(d){let value=d.trim();if(value.length<120)value+=` Consulta información educativa clara y verifica los detalles actuales con fuentes apropiadas.`;if(value.length>165){const cut=value.slice(0,162);value=cut.slice(0,Math.max(cut.lastIndexOf(' '),120)).replace(/[,:;]$/,'')+'.'}return value}
const allHtml=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','.agents','scripts'].includes(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(e.name.endsWith('.html'))allHtml.push(f)}}walk(root);
for(const file of allHtml){if(path.basename(file)==='404.html')continue;let html=fs.readFileSync(file,'utf8');const relPath=path.relative(root,path.dirname(file)),depth=relPath?relPath.split(path.sep).length:0,home=base(depth),section=pageSection(file);html=html.replace(/<nav class="site-nav" id="site-nav" aria-label="Navegación principal">[\s\S]*?<\/nav>/,nav(depth,section));html=html.replace(/<footer class="site-footer">[\s\S]*?<\/footer>/,footer(depth));if(!html.includes('rel="icon"'))html=html.replace(/(<link rel="stylesheet")/,`<link rel="icon" href="${home}assets/favicon.svg" type="image/svg+xml">$1`);const desc=(html.match(/<meta name="description" content="([^"]*)"/)||[])[1];if(desc){const next=normalizeDescription(desc);html=html.replace(`<meta name="description" content="${desc}"`,`<meta name="description" content="${next}"`).replace(`<meta property="og:description" content="${desc}"`,`<meta property="og:description" content="${next}"`).replace(`<meta name="twitter:description" content="${desc}"`,`<meta name="twitter:description" content="${next}"`)}fs.writeFileSync(file,html)}

// Replace country-guide placeholders now covered by general published guides.
for(const entry of fs.readdirSync(path.join(root,'paises'),{withFileTypes:true}).filter(e=>e.isDirectory())){const file=path.join(root,'paises',entry.name,'index.html');let html=fs.readFileSync(file,'utf8');html=html.replace(/(<article class="guide-card"><h3>Cómo entender el tipo de cambio<\/h3><p>[^<]+<\/p>)<span class="coming">Próximamente<\/span>/,`$1<a href="../../aprender/como-comparar-envios-de-dinero/">Leer guía general</a>`).replace(/(<article class="guide-card"><h3>Seguridad al recibir transferencias<\/h3><p>[^<]+<\/p>)<span class="coming">Próximamente<\/span>/,`$1<a href="../../aprender/como-evitar-estafas-financieras/">Leer guía de seguridad</a>`);fs.writeFileSync(file,html)}

const indexable=allHtml.filter(f=>path.basename(f)!=='404.html').map(f=>{const rel=path.relative(root,f).replaceAll('\\','/');return rel==='index.html'?'https://dineromundo.com/':`https://dineromundo.com/${rel.replace(/index\.html$/,'')}`}).sort((a,b)=>a==='https://dineromundo.com/'?-1:b==='https://dineromundo.com/'?1:a.localeCompare(b));
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexable.map(u=>`  <url><loc>${u}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Phase 7 generated ${pages.length} trust pages, updated ${allHtml.length} HTML files, and rebuilt ${indexable.length} sitemap URLs.`);
