import assert from 'node:assert/strict';import fs from 'node:fs';let cases=0;const ok=(v,m)=>{cases++;assert.ok(v,m)};const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const schema=read('supabase/schema.sql'),config=read('assets/js/config.js'),storage=read('assets/js/quotes/storage.js'),main=read('assets/js/main.js'),migration=read('assets/js/business/migration.js'),cloud=read('assets/js/business/cloud-storage.js');
for(const table of ['profiles','businesses','customers','quotes','invoices','incomes','expenses']){ok(new RegExp(`create table if not exists public\\.${table}`).test(schema),`${table} table`);
ok(new RegExp(`alter table public\\.${table} enable row level security`).test(schema),`${table} RLS`);}ok(/revoke all on table[\s\S]*from anon,authenticated/.test(schema),'grants revoked');
ok(/grant select,insert,update,delete[\s\S]*to authenticated/.test(schema),'authenticated grants');
ok(!/grant select[\s\S]*to anon/.test(schema),'no public select');
ok(/auth\.uid\(\)/.test(schema),'auth uid ownership');
ok(/owns_business/.test(schema),'business ownership helper');
ok(/security definer set search_path=public,pg_temp/.test(schema),'safe function search path');
ok(/check\(amount>=0\)/g.test(schema),'money constraints');
ok(!/service[_ ]?role\s*[:=]\s*['"][A-Za-z0-9]/i.test(config),'no service key');
ok(/supabaseUrl:'https:\/\/[a-z0-9]+\.supabase\.co'/.test(config)&&/supabaseAnonKey:'sb_publishable_[^']+'/.test(config),'browser-safe production configuration');
ok(!/sb_secret_/i.test(config),'no secret Supabase key');
ok(/DMLocalStorage=api/.test(storage),'local adapter retained');
ok(/DMCloudReady/.test(storage)&&/DMCloudStorage/.test(storage),'cloud routing');
ok(/name!==\'clearAll\'/.test(storage),'local delete isolated');
ok(/persistSession:true/.test(main),'session persistence');
ok(/signInWithPassword/.test(read('assets/js/account/auth.js')),'secure supported login');
ok(/resetPasswordForEmail/.test(read('assets/js/account/auth.js')),'supported recovery');
ok(/upsert\(record/.test(cloud),'idempotent cloud save');
ok(/onConflict:'business_id,id'/.test(cloud),'composite conflict key');
ok(/for\(const key of collections\)/.test(migration),'ordered collection import');
ok(/before,after,imported/.test(migration),'migration validation');
for(const page of ['cuenta/index.html','cuenta/registro/index.html','cuenta/iniciar-sesion/index.html','cuenta/recuperar/index.html']){const html=read(page);
ok(/robots" content="noindex,nofollow/.test(html),`${page} noindex`);
ok(/data-account-message/.test(html),`${page} accessible status`);}ok(/Clientes:/.test(read('assets/js/account/account-app.js')),'migration preview');
ok(/confirm\('¿Copiar/.test(read('assets/js/account/account-app.js')),'explicit migration consent');
ok(/datos locales siguen guardados/.test(read('assets/js/account/account-app.js')),'local retained');
console.log(`Phase 7 architecture: ${cases} assertions PASS`);

