-- Phase 10: recurring invoice/expense templates and duplicate-safe run claims.
alter table public.invoices add column if not exists recurring_template_id text;alter table public.invoices add column if not exists recurrence_run_id bigint;
alter table public.expenses add column if not exists recurring_template_id text;alter table public.expenses add column if not exists recurrence_run_id bigint;
create table if not exists public.recurring_templates(
 id text primary key,business_id uuid not null references public.businesses(id) on delete cascade,type text not null check(type in('invoice','expense')),
 name text not null check(char_length(name) between 1 and 160),enabled boolean not null default false,frequency text not null check(frequency in('weekly','monthly','quarterly','yearly')),
 interval integer not null default 1 check(interval between 1 and 24),start_date date not null,end_date date,next_run_at date,last_run_at date,timezone text not null default 'local' check(char_length(timezone)<=100),
 template_data jsonb not null check(jsonb_typeof(template_data)='object'),auto_create_mode text not null default 'draft' check(auto_create_mode='draft'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or end_date>=start_date)
);
create table if not exists public.recurring_runs(
 id bigint generated always as identity primary key,business_id uuid not null references public.businesses(id) on delete cascade,template_type text not null check(template_type in('invoice','expense')),
 template_id text references public.recurring_templates(id) on delete set null,scheduled_for date not null,status text not null default 'pending' check(status in('pending','completed','skipped','failed')),
 generated_entity_id text,dedupe_key text not null,error_message text check(char_length(error_message)<=500),is_manual boolean not null default false,created_at timestamptz not null default now(),completed_at timestamptz,unique(business_id,dedupe_key)
);
create or replace function public.validate_recurring_run_owner() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin if new.template_id is not null and not exists(select 1 from public.recurring_templates t where t.id=new.template_id and t.business_id=new.business_id)then raise exception using errcode='23503',message='recurring_template_business_mismatch';end if;return new;end$$;
drop trigger if exists validate_recurring_run_business on public.recurring_runs;create trigger validate_recurring_run_business before insert or update of business_id,template_id on public.recurring_runs for each row execute function public.validate_recurring_run_owner();
create index if not exists recurring_templates_due_idx on public.recurring_templates(business_id,enabled,next_run_at);create index if not exists recurring_runs_history_idx on public.recurring_runs(business_id,created_at desc);
drop trigger if exists set_recurring_templates_updated_at on public.recurring_templates;create trigger set_recurring_templates_updated_at before update on public.recurring_templates for each row execute function public.set_updated_at();
alter table public.recurring_templates enable row level security;alter table public.recurring_runs enable row level security;
revoke all on table public.recurring_templates,public.recurring_runs from anon,authenticated;grant select,insert,update,delete on public.recurring_templates to authenticated;grant select,insert,update on public.recurring_runs to authenticated;
do $$ declare t text;begin foreach t in array array['recurring_templates','recurring_runs'] loop execute format('drop policy if exists "owned %s select" on public.%I',t,t);execute format('create policy "owned %s select" on public.%I for select to authenticated using(public.owns_business(business_id))',t,t);execute format('drop policy if exists "owned %s insert" on public.%I',t,t);execute format('create policy "owned %s insert" on public.%I for insert to authenticated with check(public.owns_business(business_id))',t,t);execute format('drop policy if exists "owned %s update" on public.%I',t,t);execute format('create policy "owned %s update" on public.%I for update to authenticated using(public.owns_business(business_id)) with check(public.owns_business(business_id))',t,t);end loop;end$$;
drop policy if exists "owned recurring_templates delete" on public.recurring_templates;create policy "owned recurring_templates delete" on public.recurring_templates for delete to authenticated using(public.owns_business(business_id));
create or replace function public.enforce_recurring_template_limit() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare code text;lim integer;used_count bigint;begin if not new.enabled or(tg_op='UPDATE' and old.enabled)then return new;end if;select s.plan_code into code from public.subscriptions s where s.business_id=new.business_id and s.status in('active','trial')limit 1;code:=coalesce(code,'free');lim:=case code when'free'then 0 when'starter'then 3 when'business'then 15 else null end;if lim is null then return new;end if;select count(*)into used_count from public.recurring_templates where business_id=new.business_id and enabled and id<>new.id;if used_count>=lim then raise exception using errcode='P0001',message='plan_limit_reached:recurringTemplates';end if;return new;end$$;
drop trigger if exists enforce_recurring_template_plan_limit on public.recurring_templates;create trigger enforce_recurring_template_plan_limit before insert or update of enabled on public.recurring_templates for each row execute function public.enforce_recurring_template_limit();
